title: Rosemary Wang
description: >- # this means to ignore newlines until "baseurl:"
  About me, links to speaker slides and recordings.
twitter_username: joatmon08
github_username:  joatmon08
search_enabled: false

# Build settings
remote_theme: pmarsceill/just-the-docs
plugins:
  - jekyll-feed